SPOOL solution3.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 300

-- Whitney Chng Yia Qing
-- 6956865
-- Assignment 2 Task 3

/*Find the total quantity of all items (attribute L_QUANTITY in a table LINEITEM) ordered
by the customers from a given country (attribute N_NAME in a table NATION).*/

-- (1) Original Timing
connect tpchr/oracle
SET TIMING ON 

SELECT SUM(L_QUANTITY)
FROM LINEITEM JOIN ORDERS
ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN CUSTOMER
ON ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY
JOIN NATION
ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
WHERE N_NAME = 'INDIA';

SET TIMING OFF


-- (2) Original Plan
EXPLAIN PLAN FOR
SELECT SUM(L_QUANTITY)
FROM LINEITEM JOIN ORDERS
ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
JOIN CUSTOMER
ON ORDERS.O_CUSTKEY = CUSTOMER.C_CUSTKEY
JOIN NATION
ON CUSTOMER.C_NATIONKEY = NATION.N_NATIONKEY
WHERE N_NAME = 'INDIA';

@showplan.sql

-- (3) Denormalized
ALTER TABLE LINEITEM ADD L_NATION_NAME CHAR(25);

UPDATE LINEITEM
SET L_NATION_NAME =
(SELECT N_NAME
FROM NATION JOIN CUSTOMER
ON NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY
JOIN ORDERS
ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
WHERE ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY);

--(4)S Denormalized Timing
SET TIMING ON 

SELECT SUM(L_QUANTITY)
FROM LINEITEM 
WHERE L_NATION_NAME = 'INDIA'
GROUP BY L_NATION_NAME;

SET TIMING OFF

-- (5) Denormalized Plan
EXPLAIN PLAN FOR
SELECT SUM(L_QUANTITY)
FROM LINEITEM 
WHERE L_NATION_NAME = 'INDIA'
GROUP BY L_NATION_NAME;

@showplan.sql

-- (6)Indexed Timing
CREATE INDEX sol3_index ON LINEITEM(L_NATION_NAME);

SET TIMING ON 

SELECT SUM(L_QUANTITY)
FROM LINEITEM 
WHERE L_NATION_NAME = 'INDIA'
GROUP BY L_NATION_NAME;

SET TIMING OFF

--(7) Indexed Plan
EXPLAIN PLAN FOR
SELECT SUM(L_QUANTITY)
FROM LINEITEM 
WHERE L_NATION_NAME = 'INDIA'
GROUP BY L_NATION_NAME;

@showplan.sql

DROP INDEX sol3_index;
ALTER TABLE LINEITEM DROP COLUMN L_NATION_NAME;


spool off
