SPOOL solution1.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 300

-- Whitney Chng Yia Qing
-- 6956865
-- Assignment 2 Task 1

connect sys/oracle as sysdba
-- (1)

SELECT SEGMENT_NAME, SUM(BYTES) TOTAL_BYTES, SUM(BLOCKS) TOTAL_BLOCKS
FROM SYS.DBA_EXTENTS
WHERE SEGMENT_NAME in ('ORDERS','LINEITEM')
GROUP BY SEGMENT_NAME, BLOCKS;

-- (2) TABLESPACE SIZE = 326MB
CREATE TABLESPACE TBS_TASK1
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
SEGMENT SPACE MANAGEMENT AUTO
BLOCKSIZE 8K
DATAFILE '/home/oracle/TPCHR/TBS_TASK1.dbf'
SIZE 327M AUTOEXTEND ON;

ALTER USER TPCHR QUOTA 400M ON TBS_TASK1;

connect tpchr/oracle
-- (3)
CREATE TABLE ORDERS1992(
O_ORDERKEY	NUMBER(12)	NOT NULL,
O_CUSTKEY	NUMBER(12)	NOT NULL,
O_TOTALPRICE	NUMBER(12,2)	NOT NULL,
O_ORDERDATE	DATE		NOT NULL,
	CONSTRAINT ORDERS_PKEY1992 PRIMARY KEY (O_ORDERKEY),
	CONSTRAINT ORDER_CHECK1992 CHECK( O_TOTALPRICE >= 0))
pctfree 0 TABLESPACE TBS_TASK1;

CREATE TABLE LINEITEM1992(
L_ORDERKEY 	NUMBER(12)	NOT NULL,
L_LINENUMBER	NUMBER(12)	NOT NULL,
L_QUANTITY	NUMBER(12,2)	NOT NULL,
L_EXTENDEDPRICE NUMBER(12,2)	NOT NULL,
L_DISCOUNT	NUMBER(12,2)	NOT NULL,
L_TAX		NUMBER(12,2)	NOT NULL,
L_SHIPDATE	DATE		NOT NULL,
	CONSTRAINT LINEITEM_PKEY1992 PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
	CONSTRAINT LINEITEM_FKEY1992 FOREIGN KEY (L_ORDERKEY)
	REFERENCES ORDERS1992(O_ORDERKEY),
	CONSTRAINT LINEITEM_CHECK5 CHECK (L_QUANTITY >= 0),
	CONSTRAINT LINEITEM_CHECK6 CHECK (L_EXTENDEDPRICE >= 0),
	CONSTRAINT LINEITEM_CHECK7 CHECK (L_TAX >= 0),
	CONSTRAINT LINEITEM_CHECK8 CHECK (L_DISCOUNT BETWEEN 0.00 AND 1.00))
pctfree 0 TABLESPACE TBS_TASK1;


--(4)
INSERT INTO ORDERS1992(
SELECT O_ORDERKEY, O_CUSTKEY, O_TOTALPRICE, O_ORDERDATE
FROM ORDERS
WHERE TO_CHAR(O_ORDERDATE, 'yyyy') = '1992');

INSERT INTO LINEITEM1992(
SELECT L_ORDERKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, L_SHIPDATE
FROM LINEITEM 
JOIN ORDERS1992
ON LINEITEM.L_ORDERKEY = ORDERS1992.O_ORDERKEY);

-- (5)
ALTER TABLE ORDERS1992 DEALLOCATE UNUSED;
ALTER TABLE LINEITEM1992 DEALLOCATE UNUSED;


-- (6)
ANALYZE TABLE ORDERS1992 compute statistics;
ANALYZE TABLE LINEITEM1992 compute statistics;

connect sys/oracle as sysdba;
SELECT SEGMENT_NAME, SUM(BYTES) TOTAL_BYTES, SUM(BLOCKS) TOTAL_BLOCKS
FROM SYS.DBA_EXTENTS
WHERE SEGMENT_NAME in ('ORDERS1992','LINEITEM1992')
GROUP BY SEGMENT_NAME, BLOCKS;

DROP TABLESPACE TBS_TASK1 INCLUDING CONTENTS AND DATAFILES;

SPOOL off

