SPOOL solution4.lst

SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 300

-- Whitney Chng Yia Qing
-- 6956865
-- Assignment 3 Task 4

connect system/oracle

ALTER SYSTEM SET OPTIMIZER_MODE=ALL_ROWS;
ALTER SYSTEM SET QUERY_REWRITE_ENABLED=TRUE;
ALTER SYSTEM SET QUERY_REWRITE_INTEGRITY=ENFORCED;
GRANT CREATE MATERIALIZED VIEW TO TPCHR;
GRANT QUERY REWRITE TO TPCHR;
GRANT CREATE ANY TABLE TO TPCHR;

connect tpchr/oracle

-- 1 Processing Plans

EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_TAX, COUNT(*)
FROM LINEITEM
GROUP BY L_PARTKEY,L_TAX;

@showplan

EXPLAIN PLAN FOR
SELECT O_TOTALPRICE, COUNT(*)
FROM ORDERS
GROUP BY O_TOTALPRICE;

@showplan

EXPLAIN PLAN FOR
SELECT L_TAX, L_QUANTITY, COUNT(*)
FROM LINEITEM
GROUP BY L_TAX, L_QUANTITY;

@showplan

EXPLAIN PLAN FOR
SELECT O_CLERK, O_TOTALPRICE, COUNT(*)
FROM ORDERS
GROUP BY O_CLERK, O_TOTALPRICE;

@showplan

-- 2 Materialized Views

CREATE MATERIALIZED VIEW MV1
ENABLE QUERY REWRITE AS
(SELECT O_CLERK, O_TOTALPRICE, COUNT(*)
FROM ORDERS
GROUP BY O_CLERK, O_TOTALPRICE);

CREATE MATERIALIZED VIEW MV2
ENABLE QUERY REWRITE AS
(SELECT L_TAX, L_QUANTITY, L_PARTKEY, COUNT(*)
FROM LINEITEM
GROUP BY L_TAX, L_QUANTITY, L_PARTKEY);

-- 3 Processing Plans improved

EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_TAX, COUNT(*)
FROM LINEITEM
GROUP BY L_PARTKEY,L_TAX;

@showplan

EXPLAIN PLAN FOR
SELECT O_TOTALPRICE, COUNT(*)
FROM ORDERS
GROUP BY O_TOTALPRICE;

@showplan

EXPLAIN PLAN FOR
SELECT L_TAX, L_QUANTITY, COUNT(*)
FROM LINEITEM
GROUP BY L_TAX, L_QUANTITY;

@showplan

EXPLAIN PLAN FOR
SELECT O_CLERK, O_TOTALPRICE, COUNT(*)
FROM ORDERS
GROUP BY O_CLERK, O_TOTALPRICE;

@showplan

-- Drop Materialized Views
DROP MATERIALIZED VIEW MV1;
DROP MATERIALIZED VIEW MV2;

SPOOL OFF
