CREATE TABLE NEW_LINEITEM(
L_ORDERKEY 	NUMBER(12)	NOT NULL,
L_PARTKEY	NUMBER(12)	NOT NULL,
L_SUPPKEY	NUMBER(12)	NOT NULL,
L_LINENUMBER	NUMBER(12)	NOT NULL,
L_QUANTITY	NUMBER(12,2)	NOT NULL,
L_EXTENDEDPRICE NUMBER(12,2)	NOT NULL,
L_DISCOUNT	NUMBER(12,2)	NOT NULL,
L_TAX		NUMBER(12,2)	NOT NULL,
L_RETURNFLAG	CHAR(1)		NOT NULL,
L_LINESTATUS	CHAR(1)		NOT NULL,
L_SHIPDATE	DATE		NOT NULL,
L_COMMITDATE	DATE		NOT NULL,
L_RECEIPTDATE	DATE		NOT NULL,
L_SHIPINSTRUCT	CHAR(25)	NOT NULL,
L_SHIPMODE	CHAR(10)	NOT NULL,
L_COMMENT	VARCHAR(44)	NOT NULL,
	CONSTRAINT NLINEITEM_PKEY PRIMARY KEY (L_ORDERKEY, L_LINENUMBER),
	CONSTRAINT NLINEITEM_FKEY1 FOREIGN kEY (L_ORDERKEY)
		REFERENCES ORDERS(O_ORDERKEY),
	CONSTRAINT NLINEITEM_FKEY2 FOREIGN KEY (L_PARTKEY)
		REFERENCES PART(P_PARTKEY),
	CONSTRAINT NLINEITEM_FKEY3 FOREIGN KEY (L_PARTKEY,L_SUPPKEY)
		REFERENCES PARTSUPP(PS_PARTKEY, PS_SUPPKEY),
	CONSTRAINT NLINEITEM_FKEY4 FOREIGN kEY (L_SUPPKEY)
		REFERENCES SUPPLIER(S_SUPPKEY),
	CONSTRAINT NLINEITEM_CHECK1 CHECK (L_QUANTITY >= 0),
	CONSTRAINT NLINEITEM_CHECK2 CHECK (L_EXTENDEDPRICE >= 0),
	CONSTRAINT NLINEITEM_CHECK3 CHECK (L_TAX >= 0),
	CONSTRAINT NLINEITEM_CHECK4 CHECK (L_DISCOUNT BETWEEN 0.00 AND 1.00) );


INSERT INTO NEW_LINEITEM VALUES (10560,32481,1002,7,5,7067.4,0.2,0.05,'N','0','03-OCT-1997','07-SEP-1997','12-OCT-1997','NONE','MAIL');
INSERT INTO NEW_LINEITEM VALUES (10560,32481,1002,8,5,7067.4,0.1,0.04,'N','0','03-OCT-1997','07-SEP-1997','12-OCT-1997','NONE','MAIL');
/* Merge statement */
MERGE INTO LINEITEMS
USING NEW_LINEITEMS
ON (LINEITEM.L_ORDERKEY = NEW_LINEITEM.L_ORDERKEY) and
(LINEITEM.L_LINENUMBER = NEW_LINEITEM.L_LINENUMBER)
WHEN NOT MATCHED THEN
INSERT VALUES (NEW_LINEITEM.......)
WHEN MATCHED THEN
UPDATE SET LINEITEM.L_TAX = NEW_LINEITEM.L_TAX,
LINEITEM.L_DISCOUNT = NEW_LINEITEM.L_DISCOUNT;
/* SELECT THE UPDATE AND NEW RECORD */
SELECT *
FROM LINEITEM WHERE L_ORDERKEY = 10560;
ROLLBACK;