CREATE TABLE PORDERS(
O_ORDERKEY	NUMBER(12)	NOT NULL,
O_CUSTKEY	NUMBER(12)	NOT NULL,
O_ORDERSTATUS	CHAR(1)		NOT NULL,
O_TOTALPRICE	NUMBER(12,2)	NOT NULL,
O_ORDERDATE	DATE		NOT NULL,
O_ORDERPRIORITY CHAR(15)	NOT NULL,
O_CLERK		CHAR(15)	NOT NULL,
O_SHIPPRIORITY	NUMBER(12)	NOT NULL,
O_COMMENT	VARCHAR(79)	NOT NULL,
	CONSTRAINT ORDERS_PKEY PRIMARY KEY (O_ORDERKEY),
	CONSTRAINT ORDERS_FKEY1 FOREIGN kEY (O_CUSTKEY)
		REFERENCES CUSTOMER(C_CUSTKEY),
	CONSTRAINT ORDER_CHECK1 CHECK( O_TOTALPRICE >= 0) )
PARTITION BY RANGE (O_ORDERDATE)
(PARTITION P1 VALUES LESS THAN ('01-JAN-1993'),
PARTITION P2 VALUES LESS THAN ('01-JAN-1994'),
PARTITION P3 VALUES LESS THAN ('01-JAN-1995'),
PARTITION P4 VALUES LESS THAN ('01-JAN-1996'),
PARTITION P5 VALUES LESS THAN ('01-JAN-1997'),
PARTITION P6 VALUES LESS THAN ('01-JAN-1998'),
PARTITION P7 VALUES LESS THAN ('01-JAN-1999')
);

/* Populate the table PORDERS */
INSERT INTO PORDER (SELECT * FROM ORDERS);

/* CREATE GLOBALLY PARTITIONED INDEX */
CREATE INDEX IDX ON PORDERS(O_ORDERDATE) GLOBAL
PARTITION BY RANGE(O_ORDERDATE)
(PARTITION P_IDX_1 VALUES LESS THAN ('01-JAN-1993'),
 PARTITION P_IDX_2 VALUES LESS THAN ('01-JAN-1994'),
 PARTITION P_IDX_3 VALUES LESS THAN ('01-JAN-1995'),
 PARTITION P_IDX_4 VALUES LESS THAN ('01-JAN-1996'),
 PARTITION P_IDX_5 VALUES LESS THAN ('01-JAN-1997'),
 PARTITION P_IDX_6 VALUES LESS THAN ('01-JAN-1998'),
 PARTITION P_IDX_7 VALUES LESS THAN ('01-JAN-1999'),
 PARTITION P_IDX_8 VALUES LESS THAN (MAXVALUE) 
);

/* Use autotrace option to process a sample query that belongs to the given class such that it accesses the table ORDERS. */

set autotrace on
set autotrace traceonly

SELECT *
FROM ORDERS
WHERE O_ORDERDATE < TO_DATE('01-JAN-1996') AND O_ORDERDATE >= TO_DATE('01'JAN'1995');

SET AUTOTRACE OFF

/* Similarly, use autotrace to trace a similar query that access the relational table PORDERS. */

set autotrace on
set autotrace traceonly

SELECT *
FROM PORDERS
WHERE O_ORDERDATE < TO_DATE('01-JAN-1996') AND O_ORDERDATE >= TO_DATE('01'JAN'1995');

set autotrace off

/* Drop all indexes and the partioned table PORDERS. */
DROP INDEX IDX;
DROP TABLE PORDERS CASCADE CONSTRAINTS PURGE;


