connect system/oracle

GRANT CREATE MATERIALIZED VIEW TO tpchr;
GRANT QUERY REWRITE TO tpchr;
GRANT CREATE ANY TABLE TO tpchr;

connect tpchr/oracle

EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_SUPPKEY, SUM(L_QUANTITY)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;
  
EXPLAIN PLAN FOR
SELECT L_SUPPKEY, L_ORDERKEY, SUM(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY, L_ORDERKEY;
  
  
EXPLAIN PLAN FOR
SELECT L_SUPPKEY, L_ORDERKEY, SUM(L_QUANTITY)
FROM LINEITEM
GROUP BY L_SUPPKEY, L_ORDERKEY;
  
EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_SUPPKEY, COUNT(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;
  
  
EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_SUPPKEY, SUM(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;
  
EXPLAIN PLAN FOR
SELECT L_SUPPKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY;
  
EXPLAIN PLAN FOR
SELECT L_PARTKEY, L_SUPPKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY;
  
CREATE MATERIALIZED VIEW MV_LINEITEM_1
ENABLE QUERY REWRITE
AS
SELECT L_SUPPKEY, L_PARTKEY, L_ORDERKEY, SUM(L_QUANTITY), SUM(L_DISCOUNT), COUNT(L_DISCOUNT)
FROM LINEITEM
GROUP BY L_PARTKEY, L_SUPPKEY, L_ORDERKEY;
  
CREATE MATERIALIZED VIEW MV_LINEITEM_2
ENABLE QUERY REWRITE
AS
SELECT L_SUPPKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY;




CREATE MATERIALIZED VIEW MV_LINEITEM_3
ENABLE QUERY REWRITE
AS
SELECT L_SUPPKEY, L_PARTKEY, COUNT(DISTINCT L_DISCOUNT)
FROM LINEITEM
GROUP BY L_SUPPKEY, L_PARTKEY;