spool solution4

set echo on
set feedback on
set linesize 300
set pagesize 100

connect sys/oracle as sysdba

ALTER SYSTEM SET INMEMORY_SIZE=400M SCOPE=SPFILE;

shutdown immediate

startup

show parameters inmemory_size

SELECT POOL, ALLOC_BYTES, USED_BYTES, POPULATE_STATUS
FROM V$INMEMORY_AREA;

connect tpchr/oracle

EXPLAIN PLAN FOR
SELECT COUNT( DISTINCT L_TAX)
FROM LINEITEM 
WHERE L_SHIPINSTRUCT LIKE '%DELIVER IN PERSON%';

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(O_ORDERDATE)
FROM ORDERS;

@showplan

EXPLAIN PLAN FOR
SELECT AVG(PS_AVAILQTY)
FROM PARTSUPP;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(DISTINCT PS_COMMENT)
FROM PARTSUPP;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM ORDERS
WHERE O_TOTALPRICE > 100;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM ORDERS;

@showplan

EXPLAIN PLAN FOR
SELECT MIN(L_TAX), MAX(L_TAX)
FROM LINEITEM;

@showplan

/* Populate In-Memory area  */
ALTER TABLE LINEITEM INMEMORY NO INMEMORY(L_ORDERKEY,L_PARTKEY,L_SUPPKEY,L_LINENUMBER,                
                                          L_QUANTITY,L_EXTENDEDPRICE,L_DISCOUNT,L_RETURNFLAG,            
                                          L_LINESTATUS,L_SHIPDATE,L_COMMITDATE,L_RECEIPTDATE,
                                          L_SHIPMODE,L_COMMENT );

ALTER TABLE ORDERS INMEMORY NO INMEMORY(O_ORDERKEY,O_CUSTKEY,O_ORDERSTATUS,O_ORDERDATE,
                                        O_ORDERPRIORITY,O_CLERK,O_SHIPPRIORITY,O_COMMENT);

ALTER TABLE PARTSUPP INMEMORY NO INMEMORY(PS_PARTKEY,PS_SUPPKEY,PS_AVAILQTY,PS_SUPPLYCOST);

EXPLAIN PLAN FOR
SELECT COUNT( DISTINCT L_TAX)
FROM LINEITEM 
WHERE L_SHIPINSTRUCT LIKE '%DELIVER IN PERSON%';

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(O_ORDERDATE)
FROM ORDERS;

@showplan

EXPLAIN PLAN FOR
SELECT AVG(PS_AVAILQTY)
FROM PARTSUPP;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(DISTINCT PS_COMMENT)
FROM PARTSUPP;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM ORDERS
WHERE O_TOTALPRICE > 100;

@showplan

EXPLAIN PLAN FOR
SELECT COUNT(*)
FROM ORDERS;

@showplan

EXPLAIN PLAN FOR
SELECT MIN(L_TAX), MAX(L_TAX)
FROM LINEITEM;

@showplan

/* Excluding tables from In-Memory Area */
ALTER TABLE LINEITEM NO INMEMORY;
ALTER TABLE ORDERS NO INMEMORY;
ALTER TABLE PARTSUPP NO INMEMORY;

spool off






